<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_vaccine_patient_tests.TestVaccinePatient-20220520182707" tests="6" file="test_vaccine_patient_tests.py" time="0.052" timestamp="2022-05-20T18:27:08" failures="0" errors="5" skipped="1">
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_bad_date_signature" time="0.020" timestamp="2022-05-20T18:27:08">
		<error type="TypeError" message="get_vaccine_date() missing 1 required positional argument: 'date'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 672, in run
    self._callSetUp()
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 630, in _callSetUp
    self.setUp()
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\target\venv\build\cpython-3.8.0.final.0\lib\site-packages\freezegun\api.py", line 789, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\src\unittest\python\test_vaccine_patient_tests.py", line 29, in setUp
    my_manager.get_vaccine_date(file_test)
TypeError: get_vaccine_date() missing 1 required positional argument: 'date'
]]></error>
	</testcase>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_no_date" time="0.008" timestamp="2022-05-20T18:27:08">
		<error type="TypeError" message="get_vaccine_date() missing 1 required positional argument: 'date'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 672, in run
    self._callSetUp()
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 630, in _callSetUp
    self.setUp()
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\target\venv\build\cpython-3.8.0.final.0\lib\site-packages\freezegun\api.py", line 789, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\src\unittest\python\test_vaccine_patient_tests.py", line 29, in setUp
    my_manager.get_vaccine_date(file_test)
TypeError: get_vaccine_date() missing 1 required positional argument: 'date'
]]></error>
	</testcase>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_not_found_date_signature" time="0.008" timestamp="2022-05-20T18:27:08">
		<error type="TypeError" message="get_vaccine_date() missing 1 required positional argument: 'date'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 672, in run
    self._callSetUp()
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 630, in _callSetUp
    self.setUp()
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\target\venv\build\cpython-3.8.0.final.0\lib\site-packages\freezegun\api.py", line 789, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\src\unittest\python\test_vaccine_patient_tests.py", line 29, in setUp
    my_manager.get_vaccine_date(file_test)
TypeError: get_vaccine_date() missing 1 required positional argument: 'date'
]]></error>
	</testcase>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_ok" time="0.008" timestamp="2022-05-20T18:27:08">
		<error type="TypeError" message="get_vaccine_date() missing 1 required positional argument: 'date'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 672, in run
    self._callSetUp()
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 630, in _callSetUp
    self.setUp()
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\target\venv\build\cpython-3.8.0.final.0\lib\site-packages\freezegun\api.py", line 789, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\src\unittest\python\test_vaccine_patient_tests.py", line 29, in setUp
    my_manager.get_vaccine_date(file_test)
TypeError: get_vaccine_date() missing 1 required positional argument: 'date'
]]></error>
	</testcase>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_store_date_is_empty" time="0.008" timestamp="2022-05-20T18:27:08">
		<error type="TypeError" message="get_vaccine_date() missing 1 required positional argument: 'date'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 672, in run
    self._callSetUp()
  File "C:\Users\ALEJANDRA\AppData\Local\Programs\Python\Python38\lib\unittest\case.py", line 630, in _callSetUp
    self.setUp()
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\target\venv\build\cpython-3.8.0.final.0\lib\site-packages\freezegun\api.py", line 789, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\alejandra\desktop\uni\segundo\software_devel\g89.2022.t01.fp\src\unittest\python\test_vaccine_patient_tests.py", line 29, in setUp
    my_manager.get_vaccine_date(file_test)
TypeError: get_vaccine_date() missing 1 required positional argument: 'date'
]]></error>
	</testcase>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_no_store_date" time="0.000" timestamp="2022-05-20T18:27:08">
		<skipped type="skip" message="This exception won't be raised after the refactoring process"/>
	</testcase>
</testsuite>
